// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"stream.api/internal/database/model"
)

func newPopupAd(db *gorm.DB, opts ...gen.DOOption) popupAd {
	_popupAd := popupAd{}

	_popupAd.popupAdDo.UseDB(db, opts...)
	_popupAd.popupAdDo.UseModel(&model.PopupAd{})

	tableName := _popupAd.popupAdDo.TableName()
	_popupAd.ALL = field.NewAsterisk(tableName)
	_popupAd.ID = field.NewString(tableName, "id")
	_popupAd.UserID = field.NewString(tableName, "user_id")
	_popupAd.Type = field.NewString(tableName, "type")
	_popupAd.Label = field.NewString(tableName, "label")
	_popupAd.Value = field.NewString(tableName, "value")
	_popupAd.IsActive = field.NewBool(tableName, "is_active")
	_popupAd.MaxTriggersPerSession = field.NewInt32(tableName, "max_triggers_per_session")
	_popupAd.CreatedAt = field.NewTime(tableName, "created_at")
	_popupAd.UpdatedAt = field.NewTime(tableName, "updated_at")
	_popupAd.Version = field.NewInt64(tableName, "version")

	_popupAd.fillFieldMap()

	return _popupAd
}

type popupAd struct {
	popupAdDo popupAdDo

	ALL                   field.Asterisk
	ID                    field.String
	UserID                field.String
	Type                  field.String
	Label                 field.String
	Value                 field.String
	IsActive              field.Bool
	MaxTriggersPerSession field.Int32
	CreatedAt             field.Time
	UpdatedAt             field.Time
	Version               field.Int64

	fieldMap map[string]field.Expr
}

func (p popupAd) Table(newTableName string) *popupAd {
	p.popupAdDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p popupAd) As(alias string) *popupAd {
	p.popupAdDo.DO = *(p.popupAdDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *popupAd) updateTableName(table string) *popupAd {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.UserID = field.NewString(table, "user_id")
	p.Type = field.NewString(table, "type")
	p.Label = field.NewString(table, "label")
	p.Value = field.NewString(table, "value")
	p.IsActive = field.NewBool(table, "is_active")
	p.MaxTriggersPerSession = field.NewInt32(table, "max_triggers_per_session")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.Version = field.NewInt64(table, "version")

	p.fillFieldMap()

	return p
}

func (p *popupAd) WithContext(ctx context.Context) IPopupAdDo { return p.popupAdDo.WithContext(ctx) }

func (p popupAd) TableName() string { return p.popupAdDo.TableName() }

func (p popupAd) Alias() string { return p.popupAdDo.Alias() }

func (p popupAd) Columns(cols ...field.Expr) gen.Columns { return p.popupAdDo.Columns(cols...) }

func (p *popupAd) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *popupAd) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["type"] = p.Type
	p.fieldMap["label"] = p.Label
	p.fieldMap["value"] = p.Value
	p.fieldMap["is_active"] = p.IsActive
	p.fieldMap["max_triggers_per_session"] = p.MaxTriggersPerSession
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["version"] = p.Version
}

func (p popupAd) clone(db *gorm.DB) popupAd {
	p.popupAdDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p popupAd) replaceDB(db *gorm.DB) popupAd {
	p.popupAdDo.ReplaceDB(db)
	return p
}

type popupAdDo struct{ gen.DO }

type IPopupAdDo interface {
	gen.SubQuery
	Debug() IPopupAdDo
	WithContext(ctx context.Context) IPopupAdDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPopupAdDo
	WriteDB() IPopupAdDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPopupAdDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPopupAdDo
	Not(conds ...gen.Condition) IPopupAdDo
	Or(conds ...gen.Condition) IPopupAdDo
	Select(conds ...field.Expr) IPopupAdDo
	Where(conds ...gen.Condition) IPopupAdDo
	Order(conds ...field.Expr) IPopupAdDo
	Distinct(cols ...field.Expr) IPopupAdDo
	Omit(cols ...field.Expr) IPopupAdDo
	Join(table schema.Tabler, on ...field.Expr) IPopupAdDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPopupAdDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPopupAdDo
	Group(cols ...field.Expr) IPopupAdDo
	Having(conds ...gen.Condition) IPopupAdDo
	Limit(limit int) IPopupAdDo
	Offset(offset int) IPopupAdDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPopupAdDo
	Unscoped() IPopupAdDo
	Create(values ...*model.PopupAd) error
	CreateInBatches(values []*model.PopupAd, batchSize int) error
	Save(values ...*model.PopupAd) error
	First() (*model.PopupAd, error)
	Take() (*model.PopupAd, error)
	Last() (*model.PopupAd, error)
	Find() ([]*model.PopupAd, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PopupAd, err error)
	FindInBatches(result *[]*model.PopupAd, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PopupAd) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPopupAdDo
	Assign(attrs ...field.AssignExpr) IPopupAdDo
	Joins(fields ...field.RelationField) IPopupAdDo
	Preload(fields ...field.RelationField) IPopupAdDo
	FirstOrInit() (*model.PopupAd, error)
	FirstOrCreate() (*model.PopupAd, error)
	FindByPage(offset int, limit int) (result []*model.PopupAd, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPopupAdDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p popupAdDo) Debug() IPopupAdDo {
	return p.withDO(p.DO.Debug())
}

func (p popupAdDo) WithContext(ctx context.Context) IPopupAdDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p popupAdDo) ReadDB() IPopupAdDo {
	return p.Clauses(dbresolver.Read)
}

func (p popupAdDo) WriteDB() IPopupAdDo {
	return p.Clauses(dbresolver.Write)
}

func (p popupAdDo) Session(config *gorm.Session) IPopupAdDo {
	return p.withDO(p.DO.Session(config))
}

func (p popupAdDo) Clauses(conds ...clause.Expression) IPopupAdDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p popupAdDo) Returning(value interface{}, columns ...string) IPopupAdDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p popupAdDo) Not(conds ...gen.Condition) IPopupAdDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p popupAdDo) Or(conds ...gen.Condition) IPopupAdDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p popupAdDo) Select(conds ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p popupAdDo) Where(conds ...gen.Condition) IPopupAdDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p popupAdDo) Order(conds ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p popupAdDo) Distinct(cols ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p popupAdDo) Omit(cols ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p popupAdDo) Join(table schema.Tabler, on ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p popupAdDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p popupAdDo) RightJoin(table schema.Tabler, on ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p popupAdDo) Group(cols ...field.Expr) IPopupAdDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p popupAdDo) Having(conds ...gen.Condition) IPopupAdDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p popupAdDo) Limit(limit int) IPopupAdDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p popupAdDo) Offset(offset int) IPopupAdDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p popupAdDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPopupAdDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p popupAdDo) Unscoped() IPopupAdDo {
	return p.withDO(p.DO.Unscoped())
}

func (p popupAdDo) Create(values ...*model.PopupAd) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p popupAdDo) CreateInBatches(values []*model.PopupAd, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p popupAdDo) Save(values ...*model.PopupAd) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p popupAdDo) First() (*model.PopupAd, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PopupAd), nil
	}
}

func (p popupAdDo) Take() (*model.PopupAd, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PopupAd), nil
	}
}

func (p popupAdDo) Last() (*model.PopupAd, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PopupAd), nil
	}
}

func (p popupAdDo) Find() ([]*model.PopupAd, error) {
	result, err := p.DO.Find()
	return result.([]*model.PopupAd), err
}

func (p popupAdDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PopupAd, err error) {
	buf := make([]*model.PopupAd, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p popupAdDo) FindInBatches(result *[]*model.PopupAd, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p popupAdDo) Attrs(attrs ...field.AssignExpr) IPopupAdDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p popupAdDo) Assign(attrs ...field.AssignExpr) IPopupAdDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p popupAdDo) Joins(fields ...field.RelationField) IPopupAdDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p popupAdDo) Preload(fields ...field.RelationField) IPopupAdDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p popupAdDo) FirstOrInit() (*model.PopupAd, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PopupAd), nil
	}
}

func (p popupAdDo) FirstOrCreate() (*model.PopupAd, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PopupAd), nil
	}
}

func (p popupAdDo) FindByPage(offset int, limit int) (result []*model.PopupAd, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p popupAdDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p popupAdDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p popupAdDo) Delete(models ...*model.PopupAd) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *popupAdDo) withDO(do gen.Dao) *popupAdDo {
	p.DO = *do.(*gen.DO)
	return p
}
