// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomain = "domains"

// Domain mapped from table <domains>
type Domain struct {
	ID        string     `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	UserID    string     `gorm:"column:user_id;type:uuid;not null;index:idx_domains_user_id,priority:1" json:"user_id"`
	Name      string     `gorm:"column:name;type:text;not null" json:"name"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	Version   *int64     `gorm:"column:version;type:bigint;not null;default:1;version" json:"-"`
}

// TableName Domain's table name
func (*Domain) TableName() string {
	return TableNameDomain
}
