// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payment"

// Payment mapped from table <payment>
type Payment struct {
	ID            string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID        string    `gorm:"column:user_id;not null" json:"user_id"`
	PlanID        string    `gorm:"column:plan_id" json:"plan_id"`
	Amount        float64   `gorm:"column:amount;not null" json:"amount"`
	Currency      string    `gorm:"column:currency;not null;default:USD" json:"currency"`
	Status        string    `gorm:"column:status;not null;default:PENDING" json:"status"`
	Provider      string    `gorm:"column:provider;not null;default:STRIPE" json:"provider"`
	TransactionID string    `gorm:"column:transaction_id" json:"transaction_id"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
