// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlan = "plan"

// Plan mapped from table <plan>
type Plan struct {
	ID            string  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name          string  `gorm:"column:name;not null" json:"name"`
	Description   string  `gorm:"column:description" json:"description"`
	Price         float64 `gorm:"column:price;not null" json:"price"`
	Cycle         string  `gorm:"column:cycle;not null" json:"cycle"`
	StorageLimit  int64   `gorm:"column:storage_limit;not null" json:"storage_limit"`
	UploadLimit   int32   `gorm:"column:upload_limit;not null" json:"upload_limit"`
	DurationLimit int32   `gorm:"column:duration_limit;not null" json:"duration_limit"`
	QualityLimit  string  `gorm:"column:quality_limit;not null" json:"quality_limit"`
	Features      string  `gorm:"column:features" json:"features"`
	IsActive      bool    `gorm:"column:is_active;not null;default:true" json:"is_active"`
}

// TableName Plan's table name
func (*Plan) TableName() string {
	return TableNamePlan
}
