// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPreference = "user_preferences"

// UserPreference mapped from table <user_preferences>
type UserPreference struct {
	UserID                 string     `gorm:"column:user_id;type:uuid;primaryKey" json:"user_id"`
	Language               *string    `gorm:"column:language;type:text;not null;default:en" json:"language"`
	Locale                 *string    `gorm:"column:locale;type:text;not null;default:en" json:"locale"`
	EmailNotifications     *bool      `gorm:"column:email_notifications;type:boolean;not null;default:true" json:"email_notifications"`
	PushNotifications      *bool      `gorm:"column:push_notifications;type:boolean;not null;default:true" json:"push_notifications"`
	MarketingNotifications bool       `gorm:"column:marketing_notifications;type:boolean;not null" json:"marketing_notifications"`
	TelegramNotifications  bool       `gorm:"column:telegram_notifications;type:boolean;not null" json:"telegram_notifications"`
	Autoplay               bool       `gorm:"column:autoplay;type:boolean;not null" json:"autoplay"`
	Loop                   bool       `gorm:"column:loop;type:boolean;not null" json:"loop"`
	Muted                  bool       `gorm:"column:muted;type:boolean;not null" json:"muted"`
	ShowControls           *bool      `gorm:"column:show_controls;type:boolean;not null;default:true" json:"show_controls"`
	Pip                    *bool      `gorm:"column:pip;type:boolean;not null;default:true" json:"pip"`
	Airplay                *bool      `gorm:"column:airplay;type:boolean;not null;default:true" json:"airplay"`
	Chromecast             *bool      `gorm:"column:chromecast;type:boolean;not null;default:true" json:"chromecast"`
	CreatedAt              *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt              *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	EncrytionM3u8          bool       `gorm:"column:encrytion_m3u8;type:boolean;not null" json:"encrytion_m3u8"`
	Version                *int64     `gorm:"column:version;type:bigint;not null;default:1;version" json:"-"`
}

// TableName UserPreference's table name
func (*UserPreference) TableName() string {
	return TableNameUserPreference
}
