// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Password    string    `gorm:"column:password" json:"-"`
	Username    string    `gorm:"column:username" json:"username"`
	Avatar      string    `gorm:"column:avatar" json:"avatar"`
	Role        string    `gorm:"column:role;not null;default:USER" json:"role"`
	GoogleID    string    `gorm:"column:google_id" json:"google_id"`
	StorageUsed int64     `gorm:"column:storage_used;not null" json:"storage_used"`
	PlanID      string    `gorm:"column:plan_id" json:"plan_id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
