// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoAdConfig = "video_ad_configs"

// VideoAdConfig mapped from table <video_ad_configs>
type VideoAdConfig struct {
	VideoID      string     `gorm:"column:video_id;type:uuid;primaryKey" json:"video_id"`
	UserID       string     `gorm:"column:user_id;type:uuid;not null;index:idx_video_ad_configs_user_id,priority:1" json:"user_id"`
	AdTemplateID string     `gorm:"column:ad_template_id;type:uuid;not null" json:"ad_template_id"`
	VastTagURL   string     `gorm:"column:vast_tag_url;type:text;not null" json:"vast_tag_url"`
	AdFormat     *string    `gorm:"column:ad_format;type:character varying(50);not null;default:pre-roll" json:"ad_format"`
	Duration     *int64     `gorm:"column:duration;type:bigint" json:"duration"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	Version      *int64     `gorm:"column:version;type:bigint;not null;default:1;version" json:"-"`
}

// TableName VideoAdConfig's table name
func (*VideoAdConfig) TableName() string {
	return TableNameVideoAdConfig
}
