// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID               string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	Title            string    `gorm:"column:title;not null" json:"title"`
	Description      string    `gorm:"column:description" json:"description"`
	URL              string    `gorm:"column:url;not null" json:"url"`
	Thumbnail        string    `gorm:"column:thumbnail" json:"thumbnail"`
	HlsToken         string    `gorm:"column:hls_token" json:"hls_token"`
	HlsPath          string    `gorm:"column:hls_path" json:"hls_path"`
	Duration         int32     `gorm:"column:duration;not null" json:"duration"`
	Size             int64     `gorm:"column:size;not null" json:"size"`
	StorageType      string    `gorm:"column:storage_type;not null;default:tiktok_avatar" json:"storage_type"`
	Format           string    `gorm:"column:format;not null" json:"format"`
	Status           string    `gorm:"column:status;not null;default:PUBLIC" json:"status"`
	ProcessingStatus string    `gorm:"column:processing_status;not null;default:PENDING" json:"processing_status"`
	Views            int32     `gorm:"column:views;not null" json:"views"`
	UserID           string    `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
