// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: app/v1/account.proto

package appv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_app_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{0}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_app_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Language      *string                `protobuf:"bytes,3,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Locale        *string                `protobuf:"bytes,4,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	TelegramId    *string                `protobuf:"bytes,5,opt,name=telegram_id,json=telegramId,proto3,oneof" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeRequest) Reset() {
	*x = UpdateMeRequest{}
	mi := &file_app_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeRequest) ProtoMessage() {}

func (x *UpdateMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMeRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateMeRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateMeRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *UpdateMeRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *UpdateMeRequest) GetTelegramId() string {
	if x != nil && x.TelegramId != nil {
		return *x.TelegramId
	}
	return ""
}

type UpdateMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeResponse) Reset() {
	*x = UpdateMeResponse{}
	mi := &file_app_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeResponse) ProtoMessage() {}

func (x *UpdateMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeResponse) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMeRequest) Reset() {
	*x = DeleteMeRequest{}
	mi := &file_app_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeRequest) ProtoMessage() {}

func (x *DeleteMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeRequest.ProtoReflect.Descriptor instead.
func (*DeleteMeRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{4}
}

type ClearMyDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMyDataRequest) Reset() {
	*x = ClearMyDataRequest{}
	mi := &file_app_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMyDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMyDataRequest) ProtoMessage() {}

func (x *ClearMyDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMyDataRequest.ProtoReflect.Descriptor instead.
func (*ClearMyDataRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{5}
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_app_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{6}
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   *Preferences           `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_app_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetPreferencesResponse) GetPreferences() *Preferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdatePreferencesRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EmailNotifications     *bool                  `protobuf:"varint,1,opt,name=email_notifications,json=emailNotifications,proto3,oneof" json:"email_notifications,omitempty"`
	PushNotifications      *bool                  `protobuf:"varint,2,opt,name=push_notifications,json=pushNotifications,proto3,oneof" json:"push_notifications,omitempty"`
	MarketingNotifications *bool                  `protobuf:"varint,3,opt,name=marketing_notifications,json=marketingNotifications,proto3,oneof" json:"marketing_notifications,omitempty"`
	TelegramNotifications  *bool                  `protobuf:"varint,4,opt,name=telegram_notifications,json=telegramNotifications,proto3,oneof" json:"telegram_notifications,omitempty"`
	Autoplay               *bool                  `protobuf:"varint,5,opt,name=autoplay,proto3,oneof" json:"autoplay,omitempty"`
	Loop                   *bool                  `protobuf:"varint,6,opt,name=loop,proto3,oneof" json:"loop,omitempty"`
	Muted                  *bool                  `protobuf:"varint,7,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	ShowControls           *bool                  `protobuf:"varint,8,opt,name=show_controls,json=showControls,proto3,oneof" json:"show_controls,omitempty"`
	Pip                    *bool                  `protobuf:"varint,9,opt,name=pip,proto3,oneof" json:"pip,omitempty"`
	Airplay                *bool                  `protobuf:"varint,10,opt,name=airplay,proto3,oneof" json:"airplay,omitempty"`
	Chromecast             *bool                  `protobuf:"varint,11,opt,name=chromecast,proto3,oneof" json:"chromecast,omitempty"`
	Language               *string                `protobuf:"bytes,12,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Locale                 *string                `protobuf:"bytes,13,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_app_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePreferencesRequest) GetEmailNotifications() bool {
	if x != nil && x.EmailNotifications != nil {
		return *x.EmailNotifications
	}
	return false
}

func (x *UpdatePreferencesRequest) GetPushNotifications() bool {
	if x != nil && x.PushNotifications != nil {
		return *x.PushNotifications
	}
	return false
}

func (x *UpdatePreferencesRequest) GetMarketingNotifications() bool {
	if x != nil && x.MarketingNotifications != nil {
		return *x.MarketingNotifications
	}
	return false
}

func (x *UpdatePreferencesRequest) GetTelegramNotifications() bool {
	if x != nil && x.TelegramNotifications != nil {
		return *x.TelegramNotifications
	}
	return false
}

func (x *UpdatePreferencesRequest) GetAutoplay() bool {
	if x != nil && x.Autoplay != nil {
		return *x.Autoplay
	}
	return false
}

func (x *UpdatePreferencesRequest) GetLoop() bool {
	if x != nil && x.Loop != nil {
		return *x.Loop
	}
	return false
}

func (x *UpdatePreferencesRequest) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

func (x *UpdatePreferencesRequest) GetShowControls() bool {
	if x != nil && x.ShowControls != nil {
		return *x.ShowControls
	}
	return false
}

func (x *UpdatePreferencesRequest) GetPip() bool {
	if x != nil && x.Pip != nil {
		return *x.Pip
	}
	return false
}

func (x *UpdatePreferencesRequest) GetAirplay() bool {
	if x != nil && x.Airplay != nil {
		return *x.Airplay
	}
	return false
}

func (x *UpdatePreferencesRequest) GetChromecast() bool {
	if x != nil && x.Chromecast != nil {
		return *x.Chromecast
	}
	return false
}

func (x *UpdatePreferencesRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   *Preferences           `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_app_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePreferencesResponse) GetPreferences() *Preferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type GetUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_app_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{10}
}

type GetUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalVideos   int64                  `protobuf:"varint,2,opt,name=total_videos,json=totalVideos,proto3" json:"total_videos,omitempty"`
	TotalStorage  int64                  `protobuf:"varint,3,opt,name=total_storage,json=totalStorage,proto3" json:"total_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageResponse) Reset() {
	*x = GetUsageResponse{}
	mi := &file_app_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageResponse) ProtoMessage() {}

func (x *GetUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageResponse.ProtoReflect.Descriptor instead.
func (*GetUsageResponse) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *GetUsageResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUsageResponse) GetTotalVideos() int64 {
	if x != nil {
		return x.TotalVideos
	}
	return 0
}

func (x *GetUsageResponse) GetTotalStorage() int64 {
	if x != nil {
		return x.TotalStorage
	}
	return 0
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_app_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{12}
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_app_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type MarkNotificationReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadRequest) Reset() {
	*x = MarkNotificationReadRequest{}
	mi := &file_app_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadRequest) ProtoMessage() {}

func (x *MarkNotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *MarkNotificationReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MarkAllNotificationsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadRequest) Reset() {
	*x = MarkAllNotificationsReadRequest{}
	mi := &file_app_v1_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadRequest) ProtoMessage() {}

func (x *MarkAllNotificationsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{15}
}

type DeleteNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_app_v1_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClearNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearNotificationsRequest) Reset() {
	*x = ClearNotificationsRequest{}
	mi := &file_app_v1_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearNotificationsRequest) ProtoMessage() {}

func (x *ClearNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ClearNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_account_proto_rawDescGZIP(), []int{17}
}

var File_app_v1_account_proto protoreflect.FileDescriptor

const file_app_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x14app/v1/account.proto\x12\rstream.app.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13app/v1/common.proto\"\x0e\n" +
	"\fGetMeRequest\"8\n" +
	"\rGetMeResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.stream.app.v1.UserR\x04user\"\xf0\x01\n" +
	"\x0fUpdateMeRequest\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x03 \x01(\tH\x02R\blanguage\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\x04 \x01(\tH\x03R\x06locale\x88\x01\x01\x12$\n" +
	"\vtelegram_id\x18\x05 \x01(\tH\x04R\n" +
	"telegramId\x88\x01\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\v\n" +
	"\t_languageB\t\n" +
	"\a_localeB\x0e\n" +
	"\f_telegram_id\";\n" +
	"\x10UpdateMeResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.stream.app.v1.UserR\x04user\"\x11\n" +
	"\x0fDeleteMeRequest\"\x14\n" +
	"\x12ClearMyDataRequest\"\x17\n" +
	"\x15GetPreferencesRequest\"V\n" +
	"\x16GetPreferencesResponse\x12<\n" +
	"\vpreferences\x18\x01 \x01(\v2\x1a.stream.app.v1.PreferencesR\vpreferences\"\xe9\x05\n" +
	"\x18UpdatePreferencesRequest\x124\n" +
	"\x13email_notifications\x18\x01 \x01(\bH\x00R\x12emailNotifications\x88\x01\x01\x122\n" +
	"\x12push_notifications\x18\x02 \x01(\bH\x01R\x11pushNotifications\x88\x01\x01\x12<\n" +
	"\x17marketing_notifications\x18\x03 \x01(\bH\x02R\x16marketingNotifications\x88\x01\x01\x12:\n" +
	"\x16telegram_notifications\x18\x04 \x01(\bH\x03R\x15telegramNotifications\x88\x01\x01\x12\x1f\n" +
	"\bautoplay\x18\x05 \x01(\bH\x04R\bautoplay\x88\x01\x01\x12\x17\n" +
	"\x04loop\x18\x06 \x01(\bH\x05R\x04loop\x88\x01\x01\x12\x19\n" +
	"\x05muted\x18\a \x01(\bH\x06R\x05muted\x88\x01\x01\x12(\n" +
	"\rshow_controls\x18\b \x01(\bH\aR\fshowControls\x88\x01\x01\x12\x15\n" +
	"\x03pip\x18\t \x01(\bH\bR\x03pip\x88\x01\x01\x12\x1d\n" +
	"\aairplay\x18\n" +
	" \x01(\bH\tR\aairplay\x88\x01\x01\x12#\n" +
	"\n" +
	"chromecast\x18\v \x01(\bH\n" +
	"R\n" +
	"chromecast\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\f \x01(\tH\vR\blanguage\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\r \x01(\tH\fR\x06locale\x88\x01\x01B\x16\n" +
	"\x14_email_notificationsB\x15\n" +
	"\x13_push_notificationsB\x1a\n" +
	"\x18_marketing_notificationsB\x19\n" +
	"\x17_telegram_notificationsB\v\n" +
	"\t_autoplayB\a\n" +
	"\x05_loopB\b\n" +
	"\x06_mutedB\x10\n" +
	"\x0e_show_controlsB\x06\n" +
	"\x04_pipB\n" +
	"\n" +
	"\b_airplayB\r\n" +
	"\v_chromecastB\v\n" +
	"\t_languageB\t\n" +
	"\a_locale\"Y\n" +
	"\x19UpdatePreferencesResponse\x12<\n" +
	"\vpreferences\x18\x01 \x01(\v2\x1a.stream.app.v1.PreferencesR\vpreferences\"\x11\n" +
	"\x0fGetUsageRequest\"s\n" +
	"\x10GetUsageResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_videos\x18\x02 \x01(\x03R\vtotalVideos\x12#\n" +
	"\rtotal_storage\x18\x03 \x01(\x03R\ftotalStorage\"\x1a\n" +
	"\x18ListNotificationsRequest\"^\n" +
	"\x19ListNotificationsResponse\x12A\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1b.stream.app.v1.NotificationR\rnotifications\"-\n" +
	"\x1bMarkNotificationReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x1fMarkAllNotificationsReadRequest\"+\n" +
	"\x19DeleteNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19ClearNotificationsRequest2\x90\x05\n" +
	"\aAccount\x12B\n" +
	"\x05GetMe\x12\x1b.stream.app.v1.GetMeRequest\x1a\x1c.stream.app.v1.GetMeResponse\x12K\n" +
	"\bUpdateMe\x12\x1e.stream.app.v1.UpdateMeRequest\x1a\x1f.stream.app.v1.UpdateMeResponse\x12J\n" +
	"\bDeleteMe\x12\x1e.stream.app.v1.DeleteMeRequest\x1a\x1e.stream.app.v1.MessageResponse\x12P\n" +
	"\vClearMyData\x12!.stream.app.v1.ClearMyDataRequest\x1a\x1e.stream.app.v1.MessageResponse\x12B\n" +
	"\vGetUserById\x12\x1c.google.protobuf.StringValue\x1a\x13.stream.app.v1.User\"\x00\x12]\n" +
	"\x0eGetPreferences\x12$.stream.app.v1.GetPreferencesRequest\x1a%.stream.app.v1.GetPreferencesResponse\x12f\n" +
	"\x11UpdatePreferences\x12'.stream.app.v1.UpdatePreferencesRequest\x1a(.stream.app.v1.UpdatePreferencesResponse\x12K\n" +
	"\bGetUsage\x12\x1e.stream.app.v1.GetUsageRequest\x1a\x1f.stream.app.v1.GetUsageResponse2\x87\x04\n" +
	"\rNotifications\x12f\n" +
	"\x11ListNotifications\x12'.stream.app.v1.ListNotificationsRequest\x1a(.stream.app.v1.ListNotificationsResponse\x12b\n" +
	"\x14MarkNotificationRead\x12*.stream.app.v1.MarkNotificationReadRequest\x1a\x1e.stream.app.v1.MessageResponse\x12j\n" +
	"\x18MarkAllNotificationsRead\x12..stream.app.v1.MarkAllNotificationsReadRequest\x1a\x1e.stream.app.v1.MessageResponse\x12^\n" +
	"\x12DeleteNotification\x12(.stream.app.v1.DeleteNotificationRequest\x1a\x1e.stream.app.v1.MessageResponse\x12^\n" +
	"\x12ClearNotifications\x12(.stream.app.v1.ClearNotificationsRequest\x1a\x1e.stream.app.v1.MessageResponseB,Z*stream.api/internal/gen/proto/app/v1;appv1b\x06proto3"

var (
	file_app_v1_account_proto_rawDescOnce sync.Once
	file_app_v1_account_proto_rawDescData []byte
)

func file_app_v1_account_proto_rawDescGZIP() []byte {
	file_app_v1_account_proto_rawDescOnce.Do(func() {
		file_app_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_v1_account_proto_rawDesc), len(file_app_v1_account_proto_rawDesc)))
	})
	return file_app_v1_account_proto_rawDescData
}

var file_app_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_app_v1_account_proto_goTypes = []any{
	(*GetMeRequest)(nil),                    // 0: stream.app.v1.GetMeRequest
	(*GetMeResponse)(nil),                   // 1: stream.app.v1.GetMeResponse
	(*UpdateMeRequest)(nil),                 // 2: stream.app.v1.UpdateMeRequest
	(*UpdateMeResponse)(nil),                // 3: stream.app.v1.UpdateMeResponse
	(*DeleteMeRequest)(nil),                 // 4: stream.app.v1.DeleteMeRequest
	(*ClearMyDataRequest)(nil),              // 5: stream.app.v1.ClearMyDataRequest
	(*GetPreferencesRequest)(nil),           // 6: stream.app.v1.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),          // 7: stream.app.v1.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),        // 8: stream.app.v1.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil),       // 9: stream.app.v1.UpdatePreferencesResponse
	(*GetUsageRequest)(nil),                 // 10: stream.app.v1.GetUsageRequest
	(*GetUsageResponse)(nil),                // 11: stream.app.v1.GetUsageResponse
	(*ListNotificationsRequest)(nil),        // 12: stream.app.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),       // 13: stream.app.v1.ListNotificationsResponse
	(*MarkNotificationReadRequest)(nil),     // 14: stream.app.v1.MarkNotificationReadRequest
	(*MarkAllNotificationsReadRequest)(nil), // 15: stream.app.v1.MarkAllNotificationsReadRequest
	(*DeleteNotificationRequest)(nil),       // 16: stream.app.v1.DeleteNotificationRequest
	(*ClearNotificationsRequest)(nil),       // 17: stream.app.v1.ClearNotificationsRequest
	(*User)(nil),                            // 18: stream.app.v1.User
	(*Preferences)(nil),                     // 19: stream.app.v1.Preferences
	(*Notification)(nil),                    // 20: stream.app.v1.Notification
	(*wrapperspb.StringValue)(nil),          // 21: google.protobuf.StringValue
	(*MessageResponse)(nil),                 // 22: stream.app.v1.MessageResponse
}
var file_app_v1_account_proto_depIdxs = []int32{
	18, // 0: stream.app.v1.GetMeResponse.user:type_name -> stream.app.v1.User
	18, // 1: stream.app.v1.UpdateMeResponse.user:type_name -> stream.app.v1.User
	19, // 2: stream.app.v1.GetPreferencesResponse.preferences:type_name -> stream.app.v1.Preferences
	19, // 3: stream.app.v1.UpdatePreferencesResponse.preferences:type_name -> stream.app.v1.Preferences
	20, // 4: stream.app.v1.ListNotificationsResponse.notifications:type_name -> stream.app.v1.Notification
	0,  // 5: stream.app.v1.Account.GetMe:input_type -> stream.app.v1.GetMeRequest
	2,  // 6: stream.app.v1.Account.UpdateMe:input_type -> stream.app.v1.UpdateMeRequest
	4,  // 7: stream.app.v1.Account.DeleteMe:input_type -> stream.app.v1.DeleteMeRequest
	5,  // 8: stream.app.v1.Account.ClearMyData:input_type -> stream.app.v1.ClearMyDataRequest
	21, // 9: stream.app.v1.Account.GetUserById:input_type -> google.protobuf.StringValue
	6,  // 10: stream.app.v1.Account.GetPreferences:input_type -> stream.app.v1.GetPreferencesRequest
	8,  // 11: stream.app.v1.Account.UpdatePreferences:input_type -> stream.app.v1.UpdatePreferencesRequest
	10, // 12: stream.app.v1.Account.GetUsage:input_type -> stream.app.v1.GetUsageRequest
	12, // 13: stream.app.v1.Notifications.ListNotifications:input_type -> stream.app.v1.ListNotificationsRequest
	14, // 14: stream.app.v1.Notifications.MarkNotificationRead:input_type -> stream.app.v1.MarkNotificationReadRequest
	15, // 15: stream.app.v1.Notifications.MarkAllNotificationsRead:input_type -> stream.app.v1.MarkAllNotificationsReadRequest
	16, // 16: stream.app.v1.Notifications.DeleteNotification:input_type -> stream.app.v1.DeleteNotificationRequest
	17, // 17: stream.app.v1.Notifications.ClearNotifications:input_type -> stream.app.v1.ClearNotificationsRequest
	1,  // 18: stream.app.v1.Account.GetMe:output_type -> stream.app.v1.GetMeResponse
	3,  // 19: stream.app.v1.Account.UpdateMe:output_type -> stream.app.v1.UpdateMeResponse
	22, // 20: stream.app.v1.Account.DeleteMe:output_type -> stream.app.v1.MessageResponse
	22, // 21: stream.app.v1.Account.ClearMyData:output_type -> stream.app.v1.MessageResponse
	18, // 22: stream.app.v1.Account.GetUserById:output_type -> stream.app.v1.User
	7,  // 23: stream.app.v1.Account.GetPreferences:output_type -> stream.app.v1.GetPreferencesResponse
	9,  // 24: stream.app.v1.Account.UpdatePreferences:output_type -> stream.app.v1.UpdatePreferencesResponse
	11, // 25: stream.app.v1.Account.GetUsage:output_type -> stream.app.v1.GetUsageResponse
	13, // 26: stream.app.v1.Notifications.ListNotifications:output_type -> stream.app.v1.ListNotificationsResponse
	22, // 27: stream.app.v1.Notifications.MarkNotificationRead:output_type -> stream.app.v1.MessageResponse
	22, // 28: stream.app.v1.Notifications.MarkAllNotificationsRead:output_type -> stream.app.v1.MessageResponse
	22, // 29: stream.app.v1.Notifications.DeleteNotification:output_type -> stream.app.v1.MessageResponse
	22, // 30: stream.app.v1.Notifications.ClearNotifications:output_type -> stream.app.v1.MessageResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_app_v1_account_proto_init() }
func file_app_v1_account_proto_init() {
	if File_app_v1_account_proto != nil {
		return
	}
	file_app_v1_common_proto_init()
	file_app_v1_account_proto_msgTypes[2].OneofWrappers = []any{}
	file_app_v1_account_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_v1_account_proto_rawDesc), len(file_app_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_app_v1_account_proto_goTypes,
		DependencyIndexes: file_app_v1_account_proto_depIdxs,
		MessageInfos:      file_app_v1_account_proto_msgTypes,
	}.Build()
	File_app_v1_account_proto = out.File
	file_app_v1_account_proto_goTypes = nil
	file_app_v1_account_proto_depIdxs = nil
}
