// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: app/v1/admin.proto

package appv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_GetAdminDashboard_FullMethodName               = "/stream.app.v1.Admin/GetAdminDashboard"
	Admin_ListAdminUsers_FullMethodName                  = "/stream.app.v1.Admin/ListAdminUsers"
	Admin_GetAdminUser_FullMethodName                    = "/stream.app.v1.Admin/GetAdminUser"
	Admin_CreateAdminUser_FullMethodName                 = "/stream.app.v1.Admin/CreateAdminUser"
	Admin_UpdateAdminUser_FullMethodName                 = "/stream.app.v1.Admin/UpdateAdminUser"
	Admin_UpdateAdminUserReferralSettings_FullMethodName = "/stream.app.v1.Admin/UpdateAdminUserReferralSettings"
	Admin_UpdateAdminUserRole_FullMethodName             = "/stream.app.v1.Admin/UpdateAdminUserRole"
	Admin_DeleteAdminUser_FullMethodName                 = "/stream.app.v1.Admin/DeleteAdminUser"
	Admin_ListAdminVideos_FullMethodName                 = "/stream.app.v1.Admin/ListAdminVideos"
	Admin_GetAdminVideo_FullMethodName                   = "/stream.app.v1.Admin/GetAdminVideo"
	Admin_CreateAdminVideo_FullMethodName                = "/stream.app.v1.Admin/CreateAdminVideo"
	Admin_UpdateAdminVideo_FullMethodName                = "/stream.app.v1.Admin/UpdateAdminVideo"
	Admin_DeleteAdminVideo_FullMethodName                = "/stream.app.v1.Admin/DeleteAdminVideo"
	Admin_ListAdminPayments_FullMethodName               = "/stream.app.v1.Admin/ListAdminPayments"
	Admin_GetAdminPayment_FullMethodName                 = "/stream.app.v1.Admin/GetAdminPayment"
	Admin_CreateAdminPayment_FullMethodName              = "/stream.app.v1.Admin/CreateAdminPayment"
	Admin_UpdateAdminPayment_FullMethodName              = "/stream.app.v1.Admin/UpdateAdminPayment"
	Admin_ListAdminPlans_FullMethodName                  = "/stream.app.v1.Admin/ListAdminPlans"
	Admin_CreateAdminPlan_FullMethodName                 = "/stream.app.v1.Admin/CreateAdminPlan"
	Admin_UpdateAdminPlan_FullMethodName                 = "/stream.app.v1.Admin/UpdateAdminPlan"
	Admin_DeleteAdminPlan_FullMethodName                 = "/stream.app.v1.Admin/DeleteAdminPlan"
	Admin_ListAdminAdTemplates_FullMethodName            = "/stream.app.v1.Admin/ListAdminAdTemplates"
	Admin_GetAdminAdTemplate_FullMethodName              = "/stream.app.v1.Admin/GetAdminAdTemplate"
	Admin_CreateAdminAdTemplate_FullMethodName           = "/stream.app.v1.Admin/CreateAdminAdTemplate"
	Admin_UpdateAdminAdTemplate_FullMethodName           = "/stream.app.v1.Admin/UpdateAdminAdTemplate"
	Admin_DeleteAdminAdTemplate_FullMethodName           = "/stream.app.v1.Admin/DeleteAdminAdTemplate"
	Admin_ListAdminPopupAds_FullMethodName               = "/stream.app.v1.Admin/ListAdminPopupAds"
	Admin_GetAdminPopupAd_FullMethodName                 = "/stream.app.v1.Admin/GetAdminPopupAd"
	Admin_CreateAdminPopupAd_FullMethodName              = "/stream.app.v1.Admin/CreateAdminPopupAd"
	Admin_UpdateAdminPopupAd_FullMethodName              = "/stream.app.v1.Admin/UpdateAdminPopupAd"
	Admin_DeleteAdminPopupAd_FullMethodName              = "/stream.app.v1.Admin/DeleteAdminPopupAd"
	Admin_ListAdminPlayerConfigs_FullMethodName          = "/stream.app.v1.Admin/ListAdminPlayerConfigs"
	Admin_GetAdminPlayerConfig_FullMethodName            = "/stream.app.v1.Admin/GetAdminPlayerConfig"
	Admin_CreateAdminPlayerConfig_FullMethodName         = "/stream.app.v1.Admin/CreateAdminPlayerConfig"
	Admin_UpdateAdminPlayerConfig_FullMethodName         = "/stream.app.v1.Admin/UpdateAdminPlayerConfig"
	Admin_DeleteAdminPlayerConfig_FullMethodName         = "/stream.app.v1.Admin/DeleteAdminPlayerConfig"
	Admin_ListAdminJobs_FullMethodName                   = "/stream.app.v1.Admin/ListAdminJobs"
	Admin_GetAdminJob_FullMethodName                     = "/stream.app.v1.Admin/GetAdminJob"
	Admin_GetAdminJobLogs_FullMethodName                 = "/stream.app.v1.Admin/GetAdminJobLogs"
	Admin_CreateAdminJob_FullMethodName                  = "/stream.app.v1.Admin/CreateAdminJob"
	Admin_CancelAdminJob_FullMethodName                  = "/stream.app.v1.Admin/CancelAdminJob"
	Admin_RetryAdminJob_FullMethodName                   = "/stream.app.v1.Admin/RetryAdminJob"
	Admin_ListAdminAgents_FullMethodName                 = "/stream.app.v1.Admin/ListAdminAgents"
	Admin_RestartAdminAgent_FullMethodName               = "/stream.app.v1.Admin/RestartAdminAgent"
	Admin_UpdateAdminAgent_FullMethodName                = "/stream.app.v1.Admin/UpdateAdminAgent"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	GetAdminDashboard(ctx context.Context, in *GetAdminDashboardRequest, opts ...grpc.CallOption) (*GetAdminDashboardResponse, error)
	ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error)
	GetAdminUser(ctx context.Context, in *GetAdminUserRequest, opts ...grpc.CallOption) (*GetAdminUserResponse, error)
	CreateAdminUser(ctx context.Context, in *CreateAdminUserRequest, opts ...grpc.CallOption) (*CreateAdminUserResponse, error)
	UpdateAdminUser(ctx context.Context, in *UpdateAdminUserRequest, opts ...grpc.CallOption) (*UpdateAdminUserResponse, error)
	UpdateAdminUserReferralSettings(ctx context.Context, in *UpdateAdminUserReferralSettingsRequest, opts ...grpc.CallOption) (*UpdateAdminUserReferralSettingsResponse, error)
	UpdateAdminUserRole(ctx context.Context, in *UpdateAdminUserRoleRequest, opts ...grpc.CallOption) (*UpdateAdminUserRoleResponse, error)
	DeleteAdminUser(ctx context.Context, in *DeleteAdminUserRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	ListAdminVideos(ctx context.Context, in *ListAdminVideosRequest, opts ...grpc.CallOption) (*ListAdminVideosResponse, error)
	GetAdminVideo(ctx context.Context, in *GetAdminVideoRequest, opts ...grpc.CallOption) (*GetAdminVideoResponse, error)
	CreateAdminVideo(ctx context.Context, in *CreateAdminVideoRequest, opts ...grpc.CallOption) (*CreateAdminVideoResponse, error)
	UpdateAdminVideo(ctx context.Context, in *UpdateAdminVideoRequest, opts ...grpc.CallOption) (*UpdateAdminVideoResponse, error)
	DeleteAdminVideo(ctx context.Context, in *DeleteAdminVideoRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	ListAdminPayments(ctx context.Context, in *ListAdminPaymentsRequest, opts ...grpc.CallOption) (*ListAdminPaymentsResponse, error)
	GetAdminPayment(ctx context.Context, in *GetAdminPaymentRequest, opts ...grpc.CallOption) (*GetAdminPaymentResponse, error)
	CreateAdminPayment(ctx context.Context, in *CreateAdminPaymentRequest, opts ...grpc.CallOption) (*CreateAdminPaymentResponse, error)
	UpdateAdminPayment(ctx context.Context, in *UpdateAdminPaymentRequest, opts ...grpc.CallOption) (*UpdateAdminPaymentResponse, error)
	ListAdminPlans(ctx context.Context, in *ListAdminPlansRequest, opts ...grpc.CallOption) (*ListAdminPlansResponse, error)
	CreateAdminPlan(ctx context.Context, in *CreateAdminPlanRequest, opts ...grpc.CallOption) (*CreateAdminPlanResponse, error)
	UpdateAdminPlan(ctx context.Context, in *UpdateAdminPlanRequest, opts ...grpc.CallOption) (*UpdateAdminPlanResponse, error)
	DeleteAdminPlan(ctx context.Context, in *DeleteAdminPlanRequest, opts ...grpc.CallOption) (*DeleteAdminPlanResponse, error)
	ListAdminAdTemplates(ctx context.Context, in *ListAdminAdTemplatesRequest, opts ...grpc.CallOption) (*ListAdminAdTemplatesResponse, error)
	GetAdminAdTemplate(ctx context.Context, in *GetAdminAdTemplateRequest, opts ...grpc.CallOption) (*GetAdminAdTemplateResponse, error)
	CreateAdminAdTemplate(ctx context.Context, in *CreateAdminAdTemplateRequest, opts ...grpc.CallOption) (*CreateAdminAdTemplateResponse, error)
	UpdateAdminAdTemplate(ctx context.Context, in *UpdateAdminAdTemplateRequest, opts ...grpc.CallOption) (*UpdateAdminAdTemplateResponse, error)
	DeleteAdminAdTemplate(ctx context.Context, in *DeleteAdminAdTemplateRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	ListAdminPopupAds(ctx context.Context, in *ListAdminPopupAdsRequest, opts ...grpc.CallOption) (*ListAdminPopupAdsResponse, error)
	GetAdminPopupAd(ctx context.Context, in *GetAdminPopupAdRequest, opts ...grpc.CallOption) (*GetAdminPopupAdResponse, error)
	CreateAdminPopupAd(ctx context.Context, in *CreateAdminPopupAdRequest, opts ...grpc.CallOption) (*CreateAdminPopupAdResponse, error)
	UpdateAdminPopupAd(ctx context.Context, in *UpdateAdminPopupAdRequest, opts ...grpc.CallOption) (*UpdateAdminPopupAdResponse, error)
	DeleteAdminPopupAd(ctx context.Context, in *DeleteAdminPopupAdRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	ListAdminPlayerConfigs(ctx context.Context, in *ListAdminPlayerConfigsRequest, opts ...grpc.CallOption) (*ListAdminPlayerConfigsResponse, error)
	GetAdminPlayerConfig(ctx context.Context, in *GetAdminPlayerConfigRequest, opts ...grpc.CallOption) (*GetAdminPlayerConfigResponse, error)
	CreateAdminPlayerConfig(ctx context.Context, in *CreateAdminPlayerConfigRequest, opts ...grpc.CallOption) (*CreateAdminPlayerConfigResponse, error)
	UpdateAdminPlayerConfig(ctx context.Context, in *UpdateAdminPlayerConfigRequest, opts ...grpc.CallOption) (*UpdateAdminPlayerConfigResponse, error)
	DeleteAdminPlayerConfig(ctx context.Context, in *DeleteAdminPlayerConfigRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	ListAdminJobs(ctx context.Context, in *ListAdminJobsRequest, opts ...grpc.CallOption) (*ListAdminJobsResponse, error)
	GetAdminJob(ctx context.Context, in *GetAdminJobRequest, opts ...grpc.CallOption) (*GetAdminJobResponse, error)
	GetAdminJobLogs(ctx context.Context, in *GetAdminJobLogsRequest, opts ...grpc.CallOption) (*GetAdminJobLogsResponse, error)
	CreateAdminJob(ctx context.Context, in *CreateAdminJobRequest, opts ...grpc.CallOption) (*CreateAdminJobResponse, error)
	CancelAdminJob(ctx context.Context, in *CancelAdminJobRequest, opts ...grpc.CallOption) (*CancelAdminJobResponse, error)
	RetryAdminJob(ctx context.Context, in *RetryAdminJobRequest, opts ...grpc.CallOption) (*RetryAdminJobResponse, error)
	ListAdminAgents(ctx context.Context, in *ListAdminAgentsRequest, opts ...grpc.CallOption) (*ListAdminAgentsResponse, error)
	RestartAdminAgent(ctx context.Context, in *RestartAdminAgentRequest, opts ...grpc.CallOption) (*AdminAgentCommandResponse, error)
	UpdateAdminAgent(ctx context.Context, in *UpdateAdminAgentRequest, opts ...grpc.CallOption) (*AdminAgentCommandResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetAdminDashboard(ctx context.Context, in *GetAdminDashboardRequest, opts ...grpc.CallOption) (*GetAdminDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminDashboardResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsersResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminUser(ctx context.Context, in *GetAdminUserRequest, opts ...grpc.CallOption) (*GetAdminUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminUserResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminUser(ctx context.Context, in *CreateAdminUserRequest, opts ...grpc.CallOption) (*CreateAdminUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminUserResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminUser(ctx context.Context, in *UpdateAdminUserRequest, opts ...grpc.CallOption) (*UpdateAdminUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminUserResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminUserReferralSettings(ctx context.Context, in *UpdateAdminUserReferralSettingsRequest, opts ...grpc.CallOption) (*UpdateAdminUserReferralSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminUserReferralSettingsResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminUserReferralSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminUserRole(ctx context.Context, in *UpdateAdminUserRoleRequest, opts ...grpc.CallOption) (*UpdateAdminUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminUserRoleResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAdminUser(ctx context.Context, in *DeleteAdminUserRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Admin_DeleteAdminUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminVideos(ctx context.Context, in *ListAdminVideosRequest, opts ...grpc.CallOption) (*ListAdminVideosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminVideosResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminVideo(ctx context.Context, in *GetAdminVideoRequest, opts ...grpc.CallOption) (*GetAdminVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminVideoResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminVideo(ctx context.Context, in *CreateAdminVideoRequest, opts ...grpc.CallOption) (*CreateAdminVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminVideoResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminVideo(ctx context.Context, in *UpdateAdminVideoRequest, opts ...grpc.CallOption) (*UpdateAdminVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminVideoResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAdminVideo(ctx context.Context, in *DeleteAdminVideoRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Admin_DeleteAdminVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminPayments(ctx context.Context, in *ListAdminPaymentsRequest, opts ...grpc.CallOption) (*ListAdminPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminPaymentsResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminPayment(ctx context.Context, in *GetAdminPaymentRequest, opts ...grpc.CallOption) (*GetAdminPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminPaymentResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminPayment(ctx context.Context, in *CreateAdminPaymentRequest, opts ...grpc.CallOption) (*CreateAdminPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminPaymentResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminPayment(ctx context.Context, in *UpdateAdminPaymentRequest, opts ...grpc.CallOption) (*UpdateAdminPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminPaymentResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminPlans(ctx context.Context, in *ListAdminPlansRequest, opts ...grpc.CallOption) (*ListAdminPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminPlansResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminPlan(ctx context.Context, in *CreateAdminPlanRequest, opts ...grpc.CallOption) (*CreateAdminPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminPlanResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminPlan(ctx context.Context, in *UpdateAdminPlanRequest, opts ...grpc.CallOption) (*UpdateAdminPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminPlanResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAdminPlan(ctx context.Context, in *DeleteAdminPlanRequest, opts ...grpc.CallOption) (*DeleteAdminPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAdminPlanResponse)
	err := c.cc.Invoke(ctx, Admin_DeleteAdminPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminAdTemplates(ctx context.Context, in *ListAdminAdTemplatesRequest, opts ...grpc.CallOption) (*ListAdminAdTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminAdTemplatesResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminAdTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminAdTemplate(ctx context.Context, in *GetAdminAdTemplateRequest, opts ...grpc.CallOption) (*GetAdminAdTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminAdTemplateResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminAdTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminAdTemplate(ctx context.Context, in *CreateAdminAdTemplateRequest, opts ...grpc.CallOption) (*CreateAdminAdTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminAdTemplateResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminAdTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminAdTemplate(ctx context.Context, in *UpdateAdminAdTemplateRequest, opts ...grpc.CallOption) (*UpdateAdminAdTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminAdTemplateResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminAdTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAdminAdTemplate(ctx context.Context, in *DeleteAdminAdTemplateRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Admin_DeleteAdminAdTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminPopupAds(ctx context.Context, in *ListAdminPopupAdsRequest, opts ...grpc.CallOption) (*ListAdminPopupAdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminPopupAdsResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminPopupAds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminPopupAd(ctx context.Context, in *GetAdminPopupAdRequest, opts ...grpc.CallOption) (*GetAdminPopupAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminPopupAdResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminPopupAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminPopupAd(ctx context.Context, in *CreateAdminPopupAdRequest, opts ...grpc.CallOption) (*CreateAdminPopupAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminPopupAdResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminPopupAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminPopupAd(ctx context.Context, in *UpdateAdminPopupAdRequest, opts ...grpc.CallOption) (*UpdateAdminPopupAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminPopupAdResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminPopupAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAdminPopupAd(ctx context.Context, in *DeleteAdminPopupAdRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Admin_DeleteAdminPopupAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminPlayerConfigs(ctx context.Context, in *ListAdminPlayerConfigsRequest, opts ...grpc.CallOption) (*ListAdminPlayerConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminPlayerConfigsResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminPlayerConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminPlayerConfig(ctx context.Context, in *GetAdminPlayerConfigRequest, opts ...grpc.CallOption) (*GetAdminPlayerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminPlayerConfigResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminPlayerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminPlayerConfig(ctx context.Context, in *CreateAdminPlayerConfigRequest, opts ...grpc.CallOption) (*CreateAdminPlayerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminPlayerConfigResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminPlayerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminPlayerConfig(ctx context.Context, in *UpdateAdminPlayerConfigRequest, opts ...grpc.CallOption) (*UpdateAdminPlayerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminPlayerConfigResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminPlayerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAdminPlayerConfig(ctx context.Context, in *DeleteAdminPlayerConfigRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Admin_DeleteAdminPlayerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminJobs(ctx context.Context, in *ListAdminJobsRequest, opts ...grpc.CallOption) (*ListAdminJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminJobsResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminJob(ctx context.Context, in *GetAdminJobRequest, opts ...grpc.CallOption) (*GetAdminJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminJobResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdminJobLogs(ctx context.Context, in *GetAdminJobLogsRequest, opts ...grpc.CallOption) (*GetAdminJobLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminJobLogsResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdminJobLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAdminJob(ctx context.Context, in *CreateAdminJobRequest, opts ...grpc.CallOption) (*CreateAdminJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminJobResponse)
	err := c.cc.Invoke(ctx, Admin_CreateAdminJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CancelAdminJob(ctx context.Context, in *CancelAdminJobRequest, opts ...grpc.CallOption) (*CancelAdminJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAdminJobResponse)
	err := c.cc.Invoke(ctx, Admin_CancelAdminJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RetryAdminJob(ctx context.Context, in *RetryAdminJobRequest, opts ...grpc.CallOption) (*RetryAdminJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryAdminJobResponse)
	err := c.cc.Invoke(ctx, Admin_RetryAdminJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdminAgents(ctx context.Context, in *ListAdminAgentsRequest, opts ...grpc.CallOption) (*ListAdminAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminAgentsResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdminAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RestartAdminAgent(ctx context.Context, in *RestartAdminAgentRequest, opts ...grpc.CallOption) (*AdminAgentCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAgentCommandResponse)
	err := c.cc.Invoke(ctx, Admin_RestartAdminAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminAgent(ctx context.Context, in *UpdateAdminAgentRequest, opts ...grpc.CallOption) (*AdminAgentCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAgentCommandResponse)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
type AdminServer interface {
	GetAdminDashboard(context.Context, *GetAdminDashboardRequest) (*GetAdminDashboardResponse, error)
	ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error)
	GetAdminUser(context.Context, *GetAdminUserRequest) (*GetAdminUserResponse, error)
	CreateAdminUser(context.Context, *CreateAdminUserRequest) (*CreateAdminUserResponse, error)
	UpdateAdminUser(context.Context, *UpdateAdminUserRequest) (*UpdateAdminUserResponse, error)
	UpdateAdminUserReferralSettings(context.Context, *UpdateAdminUserReferralSettingsRequest) (*UpdateAdminUserReferralSettingsResponse, error)
	UpdateAdminUserRole(context.Context, *UpdateAdminUserRoleRequest) (*UpdateAdminUserRoleResponse, error)
	DeleteAdminUser(context.Context, *DeleteAdminUserRequest) (*MessageResponse, error)
	ListAdminVideos(context.Context, *ListAdminVideosRequest) (*ListAdminVideosResponse, error)
	GetAdminVideo(context.Context, *GetAdminVideoRequest) (*GetAdminVideoResponse, error)
	CreateAdminVideo(context.Context, *CreateAdminVideoRequest) (*CreateAdminVideoResponse, error)
	UpdateAdminVideo(context.Context, *UpdateAdminVideoRequest) (*UpdateAdminVideoResponse, error)
	DeleteAdminVideo(context.Context, *DeleteAdminVideoRequest) (*MessageResponse, error)
	ListAdminPayments(context.Context, *ListAdminPaymentsRequest) (*ListAdminPaymentsResponse, error)
	GetAdminPayment(context.Context, *GetAdminPaymentRequest) (*GetAdminPaymentResponse, error)
	CreateAdminPayment(context.Context, *CreateAdminPaymentRequest) (*CreateAdminPaymentResponse, error)
	UpdateAdminPayment(context.Context, *UpdateAdminPaymentRequest) (*UpdateAdminPaymentResponse, error)
	ListAdminPlans(context.Context, *ListAdminPlansRequest) (*ListAdminPlansResponse, error)
	CreateAdminPlan(context.Context, *CreateAdminPlanRequest) (*CreateAdminPlanResponse, error)
	UpdateAdminPlan(context.Context, *UpdateAdminPlanRequest) (*UpdateAdminPlanResponse, error)
	DeleteAdminPlan(context.Context, *DeleteAdminPlanRequest) (*DeleteAdminPlanResponse, error)
	ListAdminAdTemplates(context.Context, *ListAdminAdTemplatesRequest) (*ListAdminAdTemplatesResponse, error)
	GetAdminAdTemplate(context.Context, *GetAdminAdTemplateRequest) (*GetAdminAdTemplateResponse, error)
	CreateAdminAdTemplate(context.Context, *CreateAdminAdTemplateRequest) (*CreateAdminAdTemplateResponse, error)
	UpdateAdminAdTemplate(context.Context, *UpdateAdminAdTemplateRequest) (*UpdateAdminAdTemplateResponse, error)
	DeleteAdminAdTemplate(context.Context, *DeleteAdminAdTemplateRequest) (*MessageResponse, error)
	ListAdminPopupAds(context.Context, *ListAdminPopupAdsRequest) (*ListAdminPopupAdsResponse, error)
	GetAdminPopupAd(context.Context, *GetAdminPopupAdRequest) (*GetAdminPopupAdResponse, error)
	CreateAdminPopupAd(context.Context, *CreateAdminPopupAdRequest) (*CreateAdminPopupAdResponse, error)
	UpdateAdminPopupAd(context.Context, *UpdateAdminPopupAdRequest) (*UpdateAdminPopupAdResponse, error)
	DeleteAdminPopupAd(context.Context, *DeleteAdminPopupAdRequest) (*MessageResponse, error)
	ListAdminPlayerConfigs(context.Context, *ListAdminPlayerConfigsRequest) (*ListAdminPlayerConfigsResponse, error)
	GetAdminPlayerConfig(context.Context, *GetAdminPlayerConfigRequest) (*GetAdminPlayerConfigResponse, error)
	CreateAdminPlayerConfig(context.Context, *CreateAdminPlayerConfigRequest) (*CreateAdminPlayerConfigResponse, error)
	UpdateAdminPlayerConfig(context.Context, *UpdateAdminPlayerConfigRequest) (*UpdateAdminPlayerConfigResponse, error)
	DeleteAdminPlayerConfig(context.Context, *DeleteAdminPlayerConfigRequest) (*MessageResponse, error)
	ListAdminJobs(context.Context, *ListAdminJobsRequest) (*ListAdminJobsResponse, error)
	GetAdminJob(context.Context, *GetAdminJobRequest) (*GetAdminJobResponse, error)
	GetAdminJobLogs(context.Context, *GetAdminJobLogsRequest) (*GetAdminJobLogsResponse, error)
	CreateAdminJob(context.Context, *CreateAdminJobRequest) (*CreateAdminJobResponse, error)
	CancelAdminJob(context.Context, *CancelAdminJobRequest) (*CancelAdminJobResponse, error)
	RetryAdminJob(context.Context, *RetryAdminJobRequest) (*RetryAdminJobResponse, error)
	ListAdminAgents(context.Context, *ListAdminAgentsRequest) (*ListAdminAgentsResponse, error)
	RestartAdminAgent(context.Context, *RestartAdminAgentRequest) (*AdminAgentCommandResponse, error)
	UpdateAdminAgent(context.Context, *UpdateAdminAgentRequest) (*AdminAgentCommandResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) GetAdminDashboard(context.Context, *GetAdminDashboardRequest) (*GetAdminDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminDashboard not implemented")
}
func (UnimplementedAdminServer) ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminUsers not implemented")
}
func (UnimplementedAdminServer) GetAdminUser(context.Context, *GetAdminUserRequest) (*GetAdminUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminUser not implemented")
}
func (UnimplementedAdminServer) CreateAdminUser(context.Context, *CreateAdminUserRequest) (*CreateAdminUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminUser not implemented")
}
func (UnimplementedAdminServer) UpdateAdminUser(context.Context, *UpdateAdminUserRequest) (*UpdateAdminUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminUser not implemented")
}
func (UnimplementedAdminServer) UpdateAdminUserReferralSettings(context.Context, *UpdateAdminUserReferralSettingsRequest) (*UpdateAdminUserReferralSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminUserReferralSettings not implemented")
}
func (UnimplementedAdminServer) UpdateAdminUserRole(context.Context, *UpdateAdminUserRoleRequest) (*UpdateAdminUserRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminUserRole not implemented")
}
func (UnimplementedAdminServer) DeleteAdminUser(context.Context, *DeleteAdminUserRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdminUser not implemented")
}
func (UnimplementedAdminServer) ListAdminVideos(context.Context, *ListAdminVideosRequest) (*ListAdminVideosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminVideos not implemented")
}
func (UnimplementedAdminServer) GetAdminVideo(context.Context, *GetAdminVideoRequest) (*GetAdminVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminVideo not implemented")
}
func (UnimplementedAdminServer) CreateAdminVideo(context.Context, *CreateAdminVideoRequest) (*CreateAdminVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminVideo not implemented")
}
func (UnimplementedAdminServer) UpdateAdminVideo(context.Context, *UpdateAdminVideoRequest) (*UpdateAdminVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminVideo not implemented")
}
func (UnimplementedAdminServer) DeleteAdminVideo(context.Context, *DeleteAdminVideoRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdminVideo not implemented")
}
func (UnimplementedAdminServer) ListAdminPayments(context.Context, *ListAdminPaymentsRequest) (*ListAdminPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminPayments not implemented")
}
func (UnimplementedAdminServer) GetAdminPayment(context.Context, *GetAdminPaymentRequest) (*GetAdminPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminPayment not implemented")
}
func (UnimplementedAdminServer) CreateAdminPayment(context.Context, *CreateAdminPaymentRequest) (*CreateAdminPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminPayment not implemented")
}
func (UnimplementedAdminServer) UpdateAdminPayment(context.Context, *UpdateAdminPaymentRequest) (*UpdateAdminPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminPayment not implemented")
}
func (UnimplementedAdminServer) ListAdminPlans(context.Context, *ListAdminPlansRequest) (*ListAdminPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminPlans not implemented")
}
func (UnimplementedAdminServer) CreateAdminPlan(context.Context, *CreateAdminPlanRequest) (*CreateAdminPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminPlan not implemented")
}
func (UnimplementedAdminServer) UpdateAdminPlan(context.Context, *UpdateAdminPlanRequest) (*UpdateAdminPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminPlan not implemented")
}
func (UnimplementedAdminServer) DeleteAdminPlan(context.Context, *DeleteAdminPlanRequest) (*DeleteAdminPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdminPlan not implemented")
}
func (UnimplementedAdminServer) ListAdminAdTemplates(context.Context, *ListAdminAdTemplatesRequest) (*ListAdminAdTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminAdTemplates not implemented")
}
func (UnimplementedAdminServer) GetAdminAdTemplate(context.Context, *GetAdminAdTemplateRequest) (*GetAdminAdTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminAdTemplate not implemented")
}
func (UnimplementedAdminServer) CreateAdminAdTemplate(context.Context, *CreateAdminAdTemplateRequest) (*CreateAdminAdTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminAdTemplate not implemented")
}
func (UnimplementedAdminServer) UpdateAdminAdTemplate(context.Context, *UpdateAdminAdTemplateRequest) (*UpdateAdminAdTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminAdTemplate not implemented")
}
func (UnimplementedAdminServer) DeleteAdminAdTemplate(context.Context, *DeleteAdminAdTemplateRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdminAdTemplate not implemented")
}
func (UnimplementedAdminServer) ListAdminPopupAds(context.Context, *ListAdminPopupAdsRequest) (*ListAdminPopupAdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminPopupAds not implemented")
}
func (UnimplementedAdminServer) GetAdminPopupAd(context.Context, *GetAdminPopupAdRequest) (*GetAdminPopupAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminPopupAd not implemented")
}
func (UnimplementedAdminServer) CreateAdminPopupAd(context.Context, *CreateAdminPopupAdRequest) (*CreateAdminPopupAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminPopupAd not implemented")
}
func (UnimplementedAdminServer) UpdateAdminPopupAd(context.Context, *UpdateAdminPopupAdRequest) (*UpdateAdminPopupAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminPopupAd not implemented")
}
func (UnimplementedAdminServer) DeleteAdminPopupAd(context.Context, *DeleteAdminPopupAdRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdminPopupAd not implemented")
}
func (UnimplementedAdminServer) ListAdminPlayerConfigs(context.Context, *ListAdminPlayerConfigsRequest) (*ListAdminPlayerConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminPlayerConfigs not implemented")
}
func (UnimplementedAdminServer) GetAdminPlayerConfig(context.Context, *GetAdminPlayerConfigRequest) (*GetAdminPlayerConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminPlayerConfig not implemented")
}
func (UnimplementedAdminServer) CreateAdminPlayerConfig(context.Context, *CreateAdminPlayerConfigRequest) (*CreateAdminPlayerConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminPlayerConfig not implemented")
}
func (UnimplementedAdminServer) UpdateAdminPlayerConfig(context.Context, *UpdateAdminPlayerConfigRequest) (*UpdateAdminPlayerConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminPlayerConfig not implemented")
}
func (UnimplementedAdminServer) DeleteAdminPlayerConfig(context.Context, *DeleteAdminPlayerConfigRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdminPlayerConfig not implemented")
}
func (UnimplementedAdminServer) ListAdminJobs(context.Context, *ListAdminJobsRequest) (*ListAdminJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminJobs not implemented")
}
func (UnimplementedAdminServer) GetAdminJob(context.Context, *GetAdminJobRequest) (*GetAdminJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminJob not implemented")
}
func (UnimplementedAdminServer) GetAdminJobLogs(context.Context, *GetAdminJobLogsRequest) (*GetAdminJobLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminJobLogs not implemented")
}
func (UnimplementedAdminServer) CreateAdminJob(context.Context, *CreateAdminJobRequest) (*CreateAdminJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminJob not implemented")
}
func (UnimplementedAdminServer) CancelAdminJob(context.Context, *CancelAdminJobRequest) (*CancelAdminJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAdminJob not implemented")
}
func (UnimplementedAdminServer) RetryAdminJob(context.Context, *RetryAdminJobRequest) (*RetryAdminJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryAdminJob not implemented")
}
func (UnimplementedAdminServer) ListAdminAgents(context.Context, *ListAdminAgentsRequest) (*ListAdminAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminAgents not implemented")
}
func (UnimplementedAdminServer) RestartAdminAgent(context.Context, *RestartAdminAgentRequest) (*AdminAgentCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartAdminAgent not implemented")
}
func (UnimplementedAdminServer) UpdateAdminAgent(context.Context, *UpdateAdminAgentRequest) (*AdminAgentCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminAgent not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_GetAdminDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminDashboard(ctx, req.(*GetAdminDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminUsers(ctx, req.(*ListAdminUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminUser(ctx, req.(*GetAdminUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminUser(ctx, req.(*CreateAdminUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminUser(ctx, req.(*UpdateAdminUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminUserReferralSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminUserReferralSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminUserReferralSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminUserReferralSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminUserReferralSettings(ctx, req.(*UpdateAdminUserReferralSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminUserRole(ctx, req.(*UpdateAdminUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteAdminUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAdminUser(ctx, req.(*DeleteAdminUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminVideos(ctx, req.(*ListAdminVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminVideo(ctx, req.(*GetAdminVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminVideo(ctx, req.(*CreateAdminVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminVideo(ctx, req.(*UpdateAdminVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAdminVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAdminVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteAdminVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAdminVideo(ctx, req.(*DeleteAdminVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminPayments(ctx, req.(*ListAdminPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminPayment(ctx, req.(*GetAdminPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminPayment(ctx, req.(*CreateAdminPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminPayment(ctx, req.(*UpdateAdminPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminPlans(ctx, req.(*ListAdminPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminPlan(ctx, req.(*CreateAdminPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminPlan(ctx, req.(*UpdateAdminPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAdminPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAdminPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteAdminPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAdminPlan(ctx, req.(*DeleteAdminPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminAdTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminAdTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminAdTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminAdTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminAdTemplates(ctx, req.(*ListAdminAdTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminAdTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminAdTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminAdTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminAdTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminAdTemplate(ctx, req.(*GetAdminAdTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminAdTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminAdTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminAdTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminAdTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminAdTemplate(ctx, req.(*CreateAdminAdTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminAdTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminAdTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminAdTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminAdTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminAdTemplate(ctx, req.(*UpdateAdminAdTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAdminAdTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminAdTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAdminAdTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteAdminAdTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAdminAdTemplate(ctx, req.(*DeleteAdminAdTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminPopupAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminPopupAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminPopupAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminPopupAds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminPopupAds(ctx, req.(*ListAdminPopupAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminPopupAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminPopupAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminPopupAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminPopupAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminPopupAd(ctx, req.(*GetAdminPopupAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminPopupAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminPopupAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminPopupAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminPopupAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminPopupAd(ctx, req.(*CreateAdminPopupAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminPopupAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminPopupAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminPopupAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminPopupAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminPopupAd(ctx, req.(*UpdateAdminPopupAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAdminPopupAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminPopupAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAdminPopupAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteAdminPopupAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAdminPopupAd(ctx, req.(*DeleteAdminPopupAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminPlayerConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminPlayerConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminPlayerConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminPlayerConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminPlayerConfigs(ctx, req.(*ListAdminPlayerConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminPlayerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminPlayerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminPlayerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminPlayerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminPlayerConfig(ctx, req.(*GetAdminPlayerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminPlayerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminPlayerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminPlayerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminPlayerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminPlayerConfig(ctx, req.(*CreateAdminPlayerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminPlayerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminPlayerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminPlayerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminPlayerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminPlayerConfig(ctx, req.(*UpdateAdminPlayerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAdminPlayerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminPlayerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAdminPlayerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteAdminPlayerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAdminPlayerConfig(ctx, req.(*DeleteAdminPlayerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminJobs(ctx, req.(*ListAdminJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminJob(ctx, req.(*GetAdminJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdminJobLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminJobLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminJobLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdminJobLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminJobLogs(ctx, req.(*GetAdminJobLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAdminJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAdminJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateAdminJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAdminJob(ctx, req.(*CreateAdminJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CancelAdminJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAdminJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CancelAdminJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CancelAdminJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CancelAdminJob(ctx, req.(*CancelAdminJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RetryAdminJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryAdminJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RetryAdminJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RetryAdminJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RetryAdminJob(ctx, req.(*RetryAdminJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdminAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdminAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdminAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdminAgents(ctx, req.(*ListAdminAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RestartAdminAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAdminAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RestartAdminAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RestartAdminAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RestartAdminAgent(ctx, req.(*RestartAdminAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminAgent(ctx, req.(*UpdateAdminAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.app.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdminDashboard",
			Handler:    _Admin_GetAdminDashboard_Handler,
		},
		{
			MethodName: "ListAdminUsers",
			Handler:    _Admin_ListAdminUsers_Handler,
		},
		{
			MethodName: "GetAdminUser",
			Handler:    _Admin_GetAdminUser_Handler,
		},
		{
			MethodName: "CreateAdminUser",
			Handler:    _Admin_CreateAdminUser_Handler,
		},
		{
			MethodName: "UpdateAdminUser",
			Handler:    _Admin_UpdateAdminUser_Handler,
		},
		{
			MethodName: "UpdateAdminUserReferralSettings",
			Handler:    _Admin_UpdateAdminUserReferralSettings_Handler,
		},
		{
			MethodName: "UpdateAdminUserRole",
			Handler:    _Admin_UpdateAdminUserRole_Handler,
		},
		{
			MethodName: "DeleteAdminUser",
			Handler:    _Admin_DeleteAdminUser_Handler,
		},
		{
			MethodName: "ListAdminVideos",
			Handler:    _Admin_ListAdminVideos_Handler,
		},
		{
			MethodName: "GetAdminVideo",
			Handler:    _Admin_GetAdminVideo_Handler,
		},
		{
			MethodName: "CreateAdminVideo",
			Handler:    _Admin_CreateAdminVideo_Handler,
		},
		{
			MethodName: "UpdateAdminVideo",
			Handler:    _Admin_UpdateAdminVideo_Handler,
		},
		{
			MethodName: "DeleteAdminVideo",
			Handler:    _Admin_DeleteAdminVideo_Handler,
		},
		{
			MethodName: "ListAdminPayments",
			Handler:    _Admin_ListAdminPayments_Handler,
		},
		{
			MethodName: "GetAdminPayment",
			Handler:    _Admin_GetAdminPayment_Handler,
		},
		{
			MethodName: "CreateAdminPayment",
			Handler:    _Admin_CreateAdminPayment_Handler,
		},
		{
			MethodName: "UpdateAdminPayment",
			Handler:    _Admin_UpdateAdminPayment_Handler,
		},
		{
			MethodName: "ListAdminPlans",
			Handler:    _Admin_ListAdminPlans_Handler,
		},
		{
			MethodName: "CreateAdminPlan",
			Handler:    _Admin_CreateAdminPlan_Handler,
		},
		{
			MethodName: "UpdateAdminPlan",
			Handler:    _Admin_UpdateAdminPlan_Handler,
		},
		{
			MethodName: "DeleteAdminPlan",
			Handler:    _Admin_DeleteAdminPlan_Handler,
		},
		{
			MethodName: "ListAdminAdTemplates",
			Handler:    _Admin_ListAdminAdTemplates_Handler,
		},
		{
			MethodName: "GetAdminAdTemplate",
			Handler:    _Admin_GetAdminAdTemplate_Handler,
		},
		{
			MethodName: "CreateAdminAdTemplate",
			Handler:    _Admin_CreateAdminAdTemplate_Handler,
		},
		{
			MethodName: "UpdateAdminAdTemplate",
			Handler:    _Admin_UpdateAdminAdTemplate_Handler,
		},
		{
			MethodName: "DeleteAdminAdTemplate",
			Handler:    _Admin_DeleteAdminAdTemplate_Handler,
		},
		{
			MethodName: "ListAdminPopupAds",
			Handler:    _Admin_ListAdminPopupAds_Handler,
		},
		{
			MethodName: "GetAdminPopupAd",
			Handler:    _Admin_GetAdminPopupAd_Handler,
		},
		{
			MethodName: "CreateAdminPopupAd",
			Handler:    _Admin_CreateAdminPopupAd_Handler,
		},
		{
			MethodName: "UpdateAdminPopupAd",
			Handler:    _Admin_UpdateAdminPopupAd_Handler,
		},
		{
			MethodName: "DeleteAdminPopupAd",
			Handler:    _Admin_DeleteAdminPopupAd_Handler,
		},
		{
			MethodName: "ListAdminPlayerConfigs",
			Handler:    _Admin_ListAdminPlayerConfigs_Handler,
		},
		{
			MethodName: "GetAdminPlayerConfig",
			Handler:    _Admin_GetAdminPlayerConfig_Handler,
		},
		{
			MethodName: "CreateAdminPlayerConfig",
			Handler:    _Admin_CreateAdminPlayerConfig_Handler,
		},
		{
			MethodName: "UpdateAdminPlayerConfig",
			Handler:    _Admin_UpdateAdminPlayerConfig_Handler,
		},
		{
			MethodName: "DeleteAdminPlayerConfig",
			Handler:    _Admin_DeleteAdminPlayerConfig_Handler,
		},
		{
			MethodName: "ListAdminJobs",
			Handler:    _Admin_ListAdminJobs_Handler,
		},
		{
			MethodName: "GetAdminJob",
			Handler:    _Admin_GetAdminJob_Handler,
		},
		{
			MethodName: "GetAdminJobLogs",
			Handler:    _Admin_GetAdminJobLogs_Handler,
		},
		{
			MethodName: "CreateAdminJob",
			Handler:    _Admin_CreateAdminJob_Handler,
		},
		{
			MethodName: "CancelAdminJob",
			Handler:    _Admin_CancelAdminJob_Handler,
		},
		{
			MethodName: "RetryAdminJob",
			Handler:    _Admin_RetryAdminJob_Handler,
		},
		{
			MethodName: "ListAdminAgents",
			Handler:    _Admin_ListAdminAgents_Handler,
		},
		{
			MethodName: "RestartAdminAgent",
			Handler:    _Admin_RestartAdminAgent_Handler,
		},
		{
			MethodName: "UpdateAdminAgent",
			Handler:    _Admin_UpdateAdminAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/admin.proto",
}
